# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
